version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/django_app
    file_exists_behavior: OVERWRITE
  - source: /
    destination: /home/ubuntu/django_app/venv
    file_exists_behavior: DISALLOW

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
