version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/django_app
    file_exists_behavior: OVERWRITE

  # If you need to deploy the virtual environment, uncomment and modify the following lines:
  # - source: /venv
  #   destination: /home/ubuntu/django_app/venv
  #   file_exists_behavior: DISALLOW  # Ensure that the virtual environment isn't overwritten

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu